Traceback (most recent call last):
  File "/dockvol/climate/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/dockvol/climate/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/dockvol/climate/.venv/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/dockvol/climate/.venv/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/dockvol/climate/.venv/lib/python3.8/site-packages/nbclient/client.py", line 535, in async_execute
    await self.async_execute_cell(
  File "/dockvol/climate/.venv/lib/python3.8/site-packages/nbclient/client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/dockvol/climate/.venv/lib/python3.8/site-packages/nbclient/client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
g.setup_logging(log_fp)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-4-d17d392a3667>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mg[0m[0;34m.[0m[0msetup_logging[0m[0;34m([0m[0mlog_fp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/dockvol/pygsutils/pygsutils/general.py[0m in [0;36msetup_logging[0;34m(fp)[0m
[1;32m     18[0m     [0mrootLogger[0m [0;34m=[0m [0mlogging[0m[0;34m.[0m[0mgetLogger[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m [0;34m[0m[0m
[0;32m---> 20[0;31m     [0mfileHandler[0m [0;34m=[0m [0mlogging[0m[0;34m.[0m[0mFileHandler[0m[0;34m([0m[0mfp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     21[0m     [0mfileHandler[0m[0;34m.[0m[0msetFormatter[0m[0;34m([0m[0mformatter[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m     [0mrootLogger[0m[0;34m.[0m[0maddHandler[0m[0;34m([0m[0mfileHandler[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.8/logging/__init__.py[0m in [0;36m__init__[0;34m(self, filename, mode, encoding, delay)[0m
[1;32m   1141[0m             [0mself[0m[0;34m.[0m[0mstream[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1142[0m         [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m-> 1143[0;31m             [0mStreamHandler[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0m_open[0m[0;34m([0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1144[0m [0;34m[0m[0m
[1;32m   1145[0m     [0;32mdef[0m [0mclose[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/lib/python3.8/logging/__init__.py[0m in [0;36m_open[0;34m(self)[0m
[1;32m   1170[0m         [0mReturn[0m [0mthe[0m [0mresulting[0m [0mstream[0m[0;34m.[0m[0;34m[0m[0;34m[0m[0m
[1;32m   1171[0m         """
[0;32m-> 1172[0;31m         [0;32mreturn[0m [0mopen[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mbaseFilename[0m[0;34m,[0m [0mself[0m[0;34m.[0m[0mmode[0m[0;34m,[0m [0mencoding[0m[0;34m=[0m[0mself[0m[0;34m.[0m[0mencoding[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m   1173[0m [0;34m[0m[0m
[1;32m   1174[0m     [0;32mdef[0m [0memit[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mrecord[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/dockvol/climate/docs_book/logs/get_nyiso.log'
FileNotFoundError: [Errno 2] No such file or directory: '/dockvol/climate/docs_book/logs/get_nyiso.log'

